package net.osgiliath.acplanggraphlangchainbridge.acp;


import com.agentclientprotocol.model.ContentBlock;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * Java interface for ACP Agent Support.
 * This will be called by the Kotlin AcpAgentRunner to delegate logic to Java.
 */
public interface AcpAgentSupportBridge {
    
    /**
     * Called during ACP initialization.
     * @return Agent implementation name and capabilities.
     */
    AgentInfoBridge getAgentInfo();

    /**
     * Called when a new session is requested.
     * @param sessionId the unique identifier for the session, which can be used to track and manage the session state across multiple interactions
     *                  and should be included in all subsequent calls related to this session
     * @param cwd the current working directory for the session, which can be used by the agent to resolve file paths and manage resources in a context-aware manner
     * @param mcpServers a map of MCP server identifiers to their corresponding URLs, which the agent can use to route tool execution requests and manage interactions with external services as needed
     * @return AcpSessionBridge instance representing the active session for the agent.
     */
    AcpSessionBridge createSession(String sessionId, String cwd, Map<String, String> mcpServers);

    /**
     * Interface representing an active session for an ACP agent. This session object is created for each new session request and is used to manage the state and interactions for that specific session. It provides methods for processing prompts and streaming responses back to the caller, allowing for real-time interaction with the agent during the session lifecycle.
     */
    interface AcpSessionBridge {
        /**
         * Returns the session ID associated with this session, which can be used for logging, debugging, and correlating interactions within the same session context.
         * @return the session ID as a String
         */
        String getSessionId();

        /**
         * Processes a prompt and returns the full response as a CompletableFuture.
         * @param promptText the text of the prompt to process
         * @param resourceLinks a list of resource links associated with the prompt, which may include files, URLs, or other relevant data that the agent can use to generate its response
         * @return a CompletableFuture that will be completed with the full response once processing is finished
         */
        CompletableFuture<String> processPrompt(String promptText, List<ContentBlock.ResourceLink> resourceLinks);

        /**
         * Processes a prompt with streaming token output.
         * @param promptText the text of the prompt to process
         * @param promtResourceLinks a list of resource links associated with the prompt, which may include files, URLs, or other relevant data that the agent can use to generate its response
         * @param consumer a callback interface that will receive each token as it is generated by the model, allowing for real-time processing and response generation
         */
        void streamPrompt(String promptText, List<ContentBlock.ResourceLink> promtResourceLinks, TokenConsumer consumer);
    }

    /**
     * Callback interface for consuming tokens generated by the model in a streaming fashion.
     */
    interface TokenConsumer {
        /**
         * Called for each new token generated by the model.
         * @param token the next token in the response stream
         */
        void onNext(String token);

        /**
         * Called when the model has finished generating the response or if an error occurs.
         * This signals the end of the token stream, allowing the caller to finalize processing.
         */
        void onComplete();
        /**
         * Called if an error occurs during prompt processing or streaming.
         * @param error the Throwable representing the error that occurred, which can be used for logging, debugging, or user feedback to indicate what went wrong during the processing of the prompt
         */
        void onError(Throwable error);
    }

    /**
     * Record class representing the agent information, including its name and version. This information can be used by the ACP framework to identify the agent and its capabilities during initialization and for logging purposes.
     * @param name the name of the agent, which should be a human-readable identifier that describes the agent's purpose or functionality (e.g., "CodePromptAgent")
     * @param version the version of the agent, which should follow semantic versioning (e.g., "1.0.0") to indicate the specific iteration of the agent's implementation and can be used for compatibility checks and debugging
     */
    record AgentInfoBridge(String name, String version) {
    }
}
